[package]
name = "execut"
description = "REST API for the exec(ut) website"
version = "0.1.0"
authors = ["Sem van Nieuwenhuizen <hello@leuke-naam.fyi>"]
edition = "2021"
homepage = "https://execut.nl/"
repository = "https://github.com/StichtingSticky/execut.git"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.11", features = ["headers", "macros"] }
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.1.8", features = ["derive", "env"] }
csv = "1.2.1"
dotenvy = { version = "0.15.6", features = ["clap"] }
jsonwebtoken = "8.2.0"
serde = { version = "1.0.156", features = ["derive"] }
serde_json = "1.0.94"
sqlx = { version = "0.6.2", features = ["chrono", "postgres", "runtime-tokio-rustls", "uuid", "migrate", "offline"] }
tokio = { version = "1.26.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["cors"] }
uuid = { version = "1.3.0", features = ["serde", "v4"] }
