# fly.toml file generated for execut on 2023-03-27T22:19:13+02:00

app = "execut"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ams"

[build]
image = "execut"

[[services]]
protocol = "tcp"
internal_port = 3000
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.http_checks]]
interval = "1m40s"
timeout = "10s"
grace_period = "5s"
restart_limit = 0
method = "get"
path = "/health"
protocol = "http"
